controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint_base
        - shoulder
        - elbow
        - wrist
        - joint_end_effector
      state_publish_rate: 50
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
